export const TRENDING_FILMS_REQUEST = "TRENDING_FILMS_REQUEST";
export const TRENDING_FILMS_SUCCESS = "TRENDING_FILMS_SUCCESS";
export const TRENDING_FILMS_ERROR = "TRENDING_FILMS_ERROR";
export const SEARCH_FILM_REQUEST = "SEARCH_FILM_REQUEST";
export const SEARCH_FILM_SUCCESS = "SEARCH_FILM_SUCCESS";
export const SEARCH_FILM_ERROR = "SEARCH_FILM_ERROR";

